codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 3

coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        informational: true
      linux:
        target: 100%
        threshold: 0%
        informational: true
        flags:
          - linux
      macos:
        target: 100%
        threshold: 0%
        informational: true
        flags:
          - macos
      windows:
        target: 100%
        threshold: 0%
        informational: true
        flags:
          - windows

flags:
  linux:
    paths:
      - src/
  macos:
    paths:
      - src/
  windows:
    paths:
      - src/

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "src/*_test.mbt"
  - "src/*_wbtest.mbt"
